import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('api', {
  window: {
    minimize: () => ipcRenderer.send('window:minimize'),
    maximize: () => ipcRenderer.send('window:maximize'),
    close:    () => ipcRenderer.send('window:close'),
  },
  auth: {
    hasPassword:   () => ipcRenderer.invoke('auth:hasPassword'),
    getProfile:    () => ipcRenderer.invoke('auth:getProfile'),
    restoreRememberedSession: () => ipcRenderer.invoke('auth:restoreRememberedSession'),
    setup:         (pwd: string, name: string, email: string) => ipcRenderer.invoke('auth:setup', pwd, name, email),
    verify:        (email: string, pwd: string, remember: boolean) => ipcRenderer.invoke('auth:verify', email, pwd, remember),
    change:        (old: string, next: string) => ipcRenderer.invoke('auth:change', old, next),
    updateProfile: (name: string, email: string, address?: string, city?: string, phone?: string, signatureImage?: string) => ipcRenderer.invoke('auth:updateProfile', name, email, address, city, phone, signatureImage),
    delete:        (pwd: string) => ipcRenderer.invoke('auth:delete', pwd),
    lockSession:   () => ipcRenderer.invoke('auth:lockSession'),
    hasRecoveryKey:       () => ipcRenderer.invoke('auth:hasRecoveryKey'),
    verifyRecoveryKey:    (key: string) => ipcRenderer.invoke('auth:verifyRecoveryKey', key),
    resetWithRecoveryKey: (key: string, newPwd: string) => ipcRenderer.invoke('auth:resetWithRecoveryKey', key, newPwd),
    regenerateRecoveryKey:(pwd: string) => ipcRenderer.invoke('auth:regenerateRecoveryKey', pwd),
  },
  properties: {
    getAll: () => ipcRenderer.invoke('properties:getAll'),
    count:  () => ipcRenderer.invoke('properties:count'),
    create: (data: unknown) => ipcRenderer.invoke('properties:create', data),
    update: (id: number, data: unknown, expectedUpdatedAt: string) => ipcRenderer.invoke('properties:update', id, data, expectedUpdatedAt),
    delete: (id: number) => ipcRenderer.invoke('properties:delete', id),
  },
  tenants: {
    getAll: () => ipcRenderer.invoke('tenants:getAll'),
    count:  () => ipcRenderer.invoke('tenants:count'),
    create: (data: unknown) => ipcRenderer.invoke('tenants:create', data),
    update: (id: number, data: unknown, expectedUpdatedAt: string) => ipcRenderer.invoke('tenants:update', id, data, expectedUpdatedAt),
    delete: (id: number) => ipcRenderer.invoke('tenants:delete', id),
  },
  leases: {
    getAll: () => ipcRenderer.invoke('leases:getAll'),
    count:  () => ipcRenderer.invoke('leases:count'),
    create: (data: unknown) => ipcRenderer.invoke('leases:create', data),
    update: (id: number, data: unknown, expectedUpdatedAt: string) => ipcRenderer.invoke('leases:update', id, data, expectedUpdatedAt),
    delete: (id: number) => ipcRenderer.invoke('leases:delete', id),
  },
  payments: {
    getAll:     () => ipcRenderer.invoke('payments:getAll'),
    getByLease: (leaseId: number) => ipcRenderer.invoke('payments:getByLease', leaseId),
    getSummary: () => ipcRenderer.invoke('payments:getSummary'),
    create:     (data: unknown) => ipcRenderer.invoke('payments:create', data),
    update:     (id: number, data: unknown, expectedUpdatedAt: string) => ipcRenderer.invoke('payments:update', id, data, expectedUpdatedAt),
    markPaid:   (id: number, date: string, expectedUpdatedAt: string) => ipcRenderer.invoke('payments:markPaid', id, date, expectedUpdatedAt),
    delete:     (id: number) => ipcRenderer.invoke('payments:delete', id),
    generateMissing: () => ipcRenderer.invoke('payments:generateMissing') as Promise<{ created: number; markedLate: number }>,
    markOverdue:     () => ipcRenderer.invoke('payments:markOverdue') as Promise<number>,
  },
  paymentReminders: {
    getByPayment: (paymentId: number) => ipcRenderer.invoke('paymentReminders:getByPayment', paymentId),
    create:       (data: unknown) => ipcRenderer.invoke('paymentReminders:create', data),
  },
  inspections: {
    getAll:  () => ipcRenderer.invoke('inspections:getAll'),
    create:  (data: unknown) => ipcRenderer.invoke('inspections:create', data),
    update:  (id: number, data: unknown) => ipcRenderer.invoke('inspections:update', id, data),
    delete:  (id: number) => ipcRenderer.invoke('inspections:delete', id),
  },
  chargeReconciliations: {
    getByLease: (leaseId: number) => ipcRenderer.invoke('chargeReconciliations:getByLease', leaseId),
    create:     (data: unknown) => ipcRenderer.invoke('chargeReconciliations:create', data),
    update:     (id: number, data: unknown) => ipcRenderer.invoke('chargeReconciliations:update', id, data),
    delete:     (id: number) => ipcRenderer.invoke('chargeReconciliations:delete', id),
  },
  manualReminders: {
    getAll:  () => ipcRenderer.invoke('manualReminders:getAll'),
    create:  (data: unknown) => ipcRenderer.invoke('manualReminders:create', data),
    update:  (id: number, data: unknown) => ipcRenderer.invoke('manualReminders:update', id, data),
    delete:  (id: number) => ipcRenderer.invoke('manualReminders:delete', id),
  },
  documents: {
    getAll:    () => ipcRenderer.invoke('documents:getAll'),
    delete:    (id: number) => ipcRenderer.invoke('documents:delete', id),
    savePdf:   (leaseId: number, fileName: string, buffer: number[], docType?: string) => ipcRenderer.invoke('documents:savePdf', leaseId, fileName, buffer, docType),
    updateStatus: (id: number, status: string) => ipcRenderer.invoke('documents:updateStatus', id, status),
    readFile:  (filePath: string) => ipcRenderer.invoke('documents:readFile', filePath) as Promise<{ data: string | null; error: string | null }>,
    openFile:  (filePath: string) => ipcRenderer.invoke('documents:openFile', filePath),
  },
  exports: {
    saveFile: (fileName: string, buffer: number[], filters?: unknown) => ipcRenderer.invoke('exports:saveFile', fileName, buffer, filters),
  },
  fiscalExpenses: {
    getAll:   () => ipcRenderer.invoke('fiscalExpenses:getAll'),
    getByYear:(year: number) => ipcRenderer.invoke('fiscalExpenses:getByYear', year),
    create:   (data: unknown) => ipcRenderer.invoke('fiscalExpenses:create', data),
    update:   (id: number, data: unknown) => ipcRenderer.invoke('fiscalExpenses:update', id, data),
    delete:   (id: number) => ipcRenderer.invoke('fiscalExpenses:delete', id),
  },
  attachments: {
    getByEntity: (entityType: string, entityId: number) => ipcRenderer.invoke('attachments:getByEntity', entityType, entityId),
    getAll:      () => ipcRenderer.invoke('attachments:getAll'),
    upload:      (entityType: string, entityId: number, slot: string | null) => ipcRenderer.invoke('attachments:upload', entityType, entityId, slot),
    read:        (id: number) => ipcRenderer.invoke('attachments:read', id),
    open:        (id: number) => ipcRenderer.invoke('attachments:open', id),
    delete:      (id: number) => ipcRenderer.invoke('attachments:delete', id),
  },
  bankImports: {
    findDuplicates:  (fingerprints: string[]) => ipcRenderer.invoke('bankImports:findDuplicates', fingerprints),
    recordImported:  (entries: Array<{ fingerprint: string; tx_date: string; description: string; amount: number; payment_id: number | null }>) => ipcRenderer.invoke('bankImports:recordImported', entries),
  },
  backup: {
    create:          () => ipcRenderer.invoke('backup:create'),
    getSettings:     () => ipcRenderer.invoke('backup:getSettings'),
    updateSettings:  (patch: Record<string, unknown>) => ipcRenderer.invoke('backup:updateSettings', patch),
    pickFolder:      () => ipcRenderer.invoke('backup:pickFolder'),
    verify:          () => ipcRenderer.invoke('backup:verify'),
    preview:         () => ipcRenderer.invoke('backup:preview'),
    restoreFromPath: (filePath: string) => ipcRenderer.invoke('backup:restoreFromPath', filePath),
    openDataFolder:  () => ipcRenderer.invoke('backup:openDataFolder'),
    onAutoDone:      (cb: (_e: unknown, data: { path: string; sizeBytes: number; at: string }) => void) => {
      ipcRenderer.on('backup:autoDone', cb)
      return () => { ipcRenderer.removeListener('backup:autoDone', cb) }
    },
  },
  irl: {
    getAll:             () => ipcRenderer.invoke('irl:getAll'),
    getByQuarter:       (year: number, quarter: number) => ipcRenderer.invoke('irl:getByQuarter', year, quarter),
    getLatestForQuarter:(quarter: number) => ipcRenderer.invoke('irl:getLatestForQuarter', quarter),
    upsert:             (year: number, quarter: number, value: number) => ipcRenderer.invoke('irl:upsert', year, quarter, value),
    delete:             (id: number) => ipcRenderer.invoke('irl:delete', id),
  },
})
